# Site settings
title: Mavidurak-IO
email: mavidurak.io@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mavidurak-IO Sakarya'da yaşayan ya da Sakarya'da öğrenim 
  gören geliştiricilerin oluşturduğu topluluktur.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mavidurak.github.io" # the base hostname & protocol for your site
twitter_username: mavidurakio
github_username:  mavidurak
paginate: 7

# Build settings
markdown: kramdown


authors:
  ozziest:
    display_name: Özgür Adem Işıklı
    bio: Full Stack Developer
    avatar: https://pbs.twimg.com/profile_images/466225886530789377/P-fkjNMZ.jpeg
    email: i.ozguradem@gmail.com
    web: http://ozziest.github.io
    twitter: iozguradem
    github: ozziest
    facebook: TheMornie
    linkedin: http://tr.linkedin.com/in/ozguradem/

  frknbasaran:
    display_name: Furkan Başaran
    bio: Toyota Motor Europe bünyesinde Web Developer olarak çalışıyor.
    avatar: https://avatars0.githubusercontent.com/u/6316032?v=2&s=460
    email: frknbasaran@gmail.com
    web: furkanbasaran.com
    twitter: frknbasaran
    github: frknbasaran
    facebook: frknbasaran
    linkedin: http://tr.linkedin.com/pub/furkan-ba%C5%9Faran/73/731/b3b/

  gormelof:
    display_name: Ömer Faruk Görmel
    bio: Computer Eng. Student at Sakarya University
    avatar: https://avatars2.githubusercontent.com/u/6938857?v=2&s=460
    email: gormelomerfaruk@gmail.com
    web: http://www.omerfarukgormel.com/
    twitter: gormelof
    github: gormelof
    facebook: gormelomerfaruk
    linkedin: http://tr.linkedin.com/in/gormelof/

  kadiryaka:
    display_name: Kadir Yaka
    bio: 
    avatar: https://avatars3.githubusercontent.com/u/5338363?v=2&s=460
    email: yakakadir@gmail.com
    web: http://www.kadiryaka.com
    twitter: kadiryaka
    github: kadiryaka
    facebook: 
    linkedin: https://www.linkedin.com/pub/kadir-yaka/7a/ba1/39

  co3moz:
    display_name: Doğan Derya
    bio: Toyota Motor Europe bünyesinde Developer olarak çalışıyor.
    avatar: https://avatars3.githubusercontent.com/u/5191214?v=2&s=460
    email: co3moz@gmail.com
    web: doganderya.com
    twitter: 
    github: co3moz
    facebook: dgnderya
    linkedin: https://www.linkedin.com/pub/do%C4%9Fan-derya/93/b08/993
    
  onuraltunsoy:
    display_name: Onur Altunsoy
    bio: Student at Sakarya University and Java coder
    avatar: https://avatars2.githubusercontent.com/u/6499172?v=3&s=460
    email: onuraltunsoy28@gmail.com 
    web: 
    twitter: onuraltunsoy
    github: onuraltunsoy
    facebook: onur.altunsoy
    linkedin: https://www.linkedin.com/pub/onur-altunsoy/88/355/41
    
  ferdogan:
    display_name: Fatih Erdoğan
    bio: Intern Security Researcher at SignalSEC
    avatar: https://avatars0.githubusercontent.com/u/7360918?v=2&s=460
    email: fatiherdogan94@gmail.com
    web: http://ferdogan.net/
    twitter: FeCassie
    github: FeCassie
    facebook: f4tihErd0gan
    linkedin: fatiherdogan1
