# Site settings
title: Mavidurak-IO
email: mavidurak.io@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mavidurak-IO Sakarya'da yaşayan ya da Sakarya'da öğrenim
  gören geliştiricilerin oluşturduğu topluluktur.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mavidurak.github.io" # the base hostname & protocol for your site
twitter_username: mavidurakio
github_username:  mavidurak
paginate: 7
excerpt_separator: <!--more-->
# Build settings
markdown: kramdown
include: ["_pages"]
permalink: /:title/

authors:
  ozziest:
    display_name: Özgür Adem Işıklı
    bio: Full Stack Developer
    avatar: https://avatars2.githubusercontent.com/u/2325140?v=3&s=460
    email: i.ozguradem@gmail.com
    web: http://ozziest.github.io
    twitter: iozguradem
    github: ozziest
    facebook: TheMornie
    linkedin: http://tr.linkedin.com/in/ozguradem/

  frknbasaran:
    display_name: Furkan Başaran
    bio: Toyota Motor Europe bünyesinde Web Developer olarak çalışıyor.
    avatar: https://avatars0.githubusercontent.com/u/6316032?v=2&s=460
    email: frknbasaran@gmail.com
    web: furkanbasaran.com
    twitter: frknbasaran
    github: frknbasaran
    facebook: frknbasaran
    linkedin: http://tr.linkedin.com/pub/furkan-ba%C5%9Faran/73/731/b3b/

  okanvurdu:
    display_name: Okan Vurdu
    bio: Multimedia Apps & SIP Trunking Design Engineer at NETAS Telecommunication
    avatar: http://www.gravatar.com/avatar/2cf491a4abaf95cd1bee62cdc5e9b99e?s=460
    email: vurduo@gmail.com
    web: http://okanvurdu.com/
    twitter: vurdunio
    github: okanvurdu
    facebook: vurdunio
    linkedin: http://tr.linkedin.com/in/okanvurdu/
    
  erayarslan:
    display_name: Eray Arslan
    bio: Software Developer at Hepsiburada.com
    avatar: https://avatars1.githubusercontent.com/u/1534649?v=3&s=460
    email: relfishere@gmail.com
    web: http://eray.js.org/
    twitter: eryarslan
    github: erayarslan
    facebook: eryarslan
    linkedin: http://tr.linkedin.com/in/erayarslan/

  gormelof:
    display_name: Ömer Faruk Görmel
    bio: Computer Eng. Student at Sakarya University
    avatar: https://avatars2.githubusercontent.com/u/6938857?v=2&s=460
    email: gormelomerfaruk@gmail.com
    web: http://www.omerfarukgormel.com/
    twitter: gormelof
    github: gormelof
    facebook: gormelomerfaruk
    linkedin: http://tr.linkedin.com/in/gormelof/

  kadiryaka:
    display_name: Kadir Yaka
    bio:
    avatar: https://avatars3.githubusercontent.com/u/5338363?v=2&s=460
    email: yakakadir@gmail.com
    web: http://www.kadiryaka.com
    twitter: kadiryaka
    github: kadiryaka
    facebook:
    linkedin: https://www.linkedin.com/pub/kadir-yaka/7a/ba1/39

  co3moz:
    display_name: Doğan Derya
    bio: Toyota Motor Europe bünyesinde Developer olarak çalışıyor.
    avatar: https://avatars3.githubusercontent.com/u/5191214?v=2&s=460
    email: co3moz@gmail.com
    web: doganderya.com
    twitter:
    github: co3moz
    facebook: dgnderya
    linkedin: https://www.linkedin.com/pub/do%C4%9Fan-derya/93/b08/993

  onuraltunsoy:
    display_name: Onur Altunsoy
    bio: Student at Sakarya University and Java coder
    avatar: https://avatars2.githubusercontent.com/u/6499172?v=3&s=460
    email: onuraltunsoy28@gmail.com
    web:
    twitter: onuraltunsoy
    github: onuraltunsoy
    facebook: onur.altunsoy
    linkedin: https://www.linkedin.com/pub/onur-altunsoy/88/355/41

  ferdogan:
    display_name: Fatih Erdoğan
    bio: Intern Security Researcher at SignalSEC
    avatar: https://avatars0.githubusercontent.com/u/7360918?v=2&s=460
    email: fatiherdogan94@gmail.com
    web: http://ferdogan.net/
    twitter: FeCassie
    github: FeCassie
    facebook: f4tihErd0gan
    linkedin: https://tr.linkedin.com/in/fatiherdogan1


  emrekose26:
    display_name: Emre Köse
    bio: Front-end Developer at Rex Yazılım
    avatar: https://avatars0.githubusercontent.com/u/9356878?v=3&s=460
    email: e.kose26@gmail.com
    web: http://emre-kose.net/
    twitter: ekose26
    github: emrekose26
    facebook: ekose26
    linkedin: https://www.linkedin.com/pub/emre-k%C3%B6se/a2/b16/a84  


